### ISSUE TITLE
Single Reponsabily Principle (1)

### ISSUE THREAD

**Issue by waldaara** [Salman1057/AirLineReservationSystem#3]

**Comment by recluzegeek** [comment]
Hi! Thank you for reviewing the source code and I acknowledge, I should've
programmed my project the way you're suggesting to make the code more
modular, organized and clear. Yet at that time,  my only ambition was to
make an AirLine System with new features that'd never been implemented
earlier in a basic OOP project like flight distance calculations, arrival
time calculations, random destinations and others that I've forgot over the
time, Along the way, I didn't care about the SRP and OCP of OOP and also
not learned that in the course but now I know about OCP only because of
your issues and thanks for that.

I've read all your issues via github email notifications and learnt along
the way. Now I'm kind of busy in AI and MERN and not finding enough time to
adjust your suggestions in the codebase. If you, yourself, couldn't find
the time to make changes and do a PR upstream, you should reopen the issues
with your comments still so others landing on the repo could know the
present issues and try to mitigate those issues. The class diagrams are
also very much helpful in understanding your suggestions so also attach
them there.

Regards,
@RecluzeGeek
